language: c
dist: bionic
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - pkg-config gfortran netcdf-bin libnetcdf-dev libnetcdff-dev openmpi-bin libopenmpi-dev wget

env:

before_script:

script:
  - autoreconf -i
  - ./configure
  - make -j distcheck
